name: get_reports
description: A Dart microservice for map-related functionality.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  dio: ^5.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  yaml: ^3.1.2
  path: ^1.8.3
  http: ^0.13.0
  polyline_codec: ^0.1.6          # Route display
  firebase_admin: ^0.3.0+2
  cloud_firestore: ^5.6.7
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.7.0
  googleapis_auth: ^1.4.0

dev_dependencies:
  lints: ^2.1.1