# Application metadata
name: access                      # Package identifier (lowercase_with_underscores)
description: "ACCESS"             # Short app description
publish_to: 'none'                # Disables pub.dev publishing

# Versioning (Major.Minor.Patch+Build)
version: 1.0.0+1

# Development environment requirements
environment:
  sdk: ^3.7.0                     # Minimum Dart SDK version

# Core dependencies
dependencies:

  flutter:
    sdk: flutter                  # Flutter framework
  flutter_secure_storage: ^9.0.0  # Encrypted storage solution
  flutter_bloc: ^9.1.0            # State management library
  bloc: ^9.0.0                    # BLoC pattern implementation
  dio: ^5.0.0                     # HTTP client
  image_picker: ^1.0.4            # Image selection from device
  intl: ^0.19.0                   # Internationalization utilities
  uuid: ^4.5.1                    # Unique ID generation
  device_info_plus: ^11.4.0       # Device metadata access
  shared_preferences: ^2.2.2      # Persistent key-value storage
  html: ^0.15.0
  js: ^0.6.3
  web: ^1.1.1
  syncfusion_flutter_datepicker: ^29.2.4
  fuzzywuzzy: ^1.2.0
  diacritic: ^0.1.3
  flutter_compass: ^0.8.1
  flutter_tts: ^4.2.2
  flutter_background_geolocation: ^4.12.0
  flutter_local_notifications: ^19.2.1
  access_models:
    path: ../backend/models

    # Maps & Geolocation stack
  mapbox_maps_flutter: ^2.7.0     # Mapbox integration
  flutter_polyline_points: ^2.1.0 # Route polyline rendering
  geolocator: ^14.0.0             # Location services
  geocoding: ^3.0.0               # Address/coordinates conversion
  permission_handler: ^12.0.0+1   # Runtime permission management
  polyline_codec: ^0.1.6          # Route display

  # Firebase ecosystem
  cloud_firestore: ^5.6.6         # NoSQL database
  cloud_functions: ^5.4.0         # Serverless functions
  firebase_auth: ^5.5.2           # Authentication service
  firebase_core: ^3.13.0          # Firebase core SDK
  firebase_database: ^11.3.5      # Realtime database
  firebase_messaging: ^15.2.5     # Push notifications
  firebase_storage: ^12.4.5       # Cloud file storage
  google_sign_in: ^6.1.4          # Google OAuth integration

  # UI components
  country_icons: ^3.0.0           # Country flag icons
  cupertino_icons: ^1.0.8         # iOS-style icons
  email_validator: ^3.0.0         # Email format validation
  equatable: ^2.0.5               # Value comparison utilities
  url_launcher: ^6.1.5
  share_plus: ^11.0.0              # Share functionality
  app_links: ^6.4.0                # Universal link handling

# Development tools
dev_dependencies:
  flutter_test:
    sdk: flutter                  # Testing framework
  flutter_launcher_icons: ^0.14.3 # App icon generation
  flutter_lints: ^5.0.0           # Code quality analysis

# App icon configuration
flutter_icons:
  android: true                  # Generate Android icons
  ios: true                      # Generate iOS icons
  image_path: "assets/images/logo.png" # Source image
  pin: "assets/images/pin.png"   # Map marker icon

# Flutter-specific configuration
flutter:
  uses-material-design: true     # Enable Material icons
  
  # Asset management
  assets:
    - assets/images/             # Image resources directory