version: '3.8'

services:
  gateway:
    build: ./backend/gateway
    ports:
      - "9090:9090"
    networks:
      - my_network
    secrets:
      - mapbox_token
    depends_on:
      - search_service

  search_service:
    build: ./services/search_service
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - my_network

secrets:
  mapbox_token:
    external: true

networks:
  my_network:
    driver: overlay