services:
  gateway:
    build: ./gateway
    ports:
      - "9090:9090"
    networks:
      - access
    depends_on:
      - search_service

  search_service:
    build: ./services/search_service
    deploy:
      replicas: 1
    ports:
      - "80:8080"
    networks:
      - access

secrets:
  mapbox_token:
    external: true

networks:
  access:
    driver: bridge