name: access
description: general yaml for all backend
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  shelf: ^1.4.0
  yaml: ^3.1.2
  path: ^1.8.3
  shelf_router: ^1.0.0
  cloud_firestore: ^5.6.6         # NoSQL database
  firebase_core: ^3.13.0          # Firebase core SDK

dev_dependencies:
  lints: ^2.1.1

