version: "3.8"

services:
  gateway:
    image: gateway
    ports:
      - "9090:9090"
    networks:
      - internal
    depends_on:
      - search_service

  search_service:
    image: search_service
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    ports:
      - "8080:8080"
    networks:
      - internal

  map_service:
    image: map_service
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    ports:
      - "8081:8081"
    networks:
      - internal

  update_service:
    image: update_service
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    ports:
      - "8082:8082"
    networks:
      - internal

networks:
  internal:
    driver: overlay