version: "3.8"

services:
  search_service:
    image: search_service
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    ports:
      - "80:8080"
    networks:
      - internal

  gateway:
    image: gateway
    ports:
      - "9090:9090"
    networks:
      - internal
    depends_on:
      - search_service

networks:
  internal:
    driver: overlay