version: "3.8"

services:
  search_service:
    build: ./services/search_service
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - internal

  gateway:
    build: ./gateway
    ports:
      - "9090:9090"
    networks:
      - internal
    depends_on:
      - search_service

networks:
  internal:
    driver: overlay