name: search_service
description: A Dart microservice for handling search functionality.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  yaml: ^3.1.2
  path: ^1.8.3

# Optional: For Firebase Auth verification (if needed)
# firebase_admin: ^0.2.0 # Note: still experimental

dev_dependencies:
  lints: ^5.1.1
